### ISSUE TITLE
Grammar/Spelling check for the text displayed

### ISSUE THREAD

**Issue by anaghamittal** [KristiforMilchev/RokonoControl#5]
**Spell check**
The spellings on the website should be absolutely correct and reviewed by more than one people so there are no chances of error.

The attached screenshot shows the wrong spelling of "Different" which is written as "Diffrent".

![Screenshot (42)](https://user-images.githubusercontent.com/43825882/77846685-65e99100-71d5-11ea-8e11-a077602390a3.png)

**Comment by KristiforMilchev** [comment]
Thank you for pointing out the mistake I will fix it as soon as possible, however I must close this issue as its not regarding to the current project but rather to the official webpage of the project that is not open sourced. But if you find any other mistakes, please do point them in other issues if they are regarding to the platform or the cli and if its something related to the page just send It over private message.
